### PR TITLE
upgraded ember-cli and moved from bower to npm

### PR DESCRIPTION
**Pull request by aklkv**
Loading directly from github because repo author did not publish a new version to npm in a long time.

### CODE REVIEW

**Comment by johnotander** [comment]
Hey @aklkv, thanks for the contribution! 🍻 

Unfortunately I don't have time to maintain this repo anymore. Would you be interested in becoming a contributor, if so I could add you as an owner on npm as well.

**Comment by aklkv** [comment]
@johnotander This sounds great, thank you! I am also planning to take over the weather-icons library as it's not maintained at the moment.

**Comment by johnotander** [comment]
Invite sent to become a collaborator, if you send along your npm username as well I'll add you as an owner to the npm package. And thanks! 🙏 ❤️

**Comment by aklkv** [comment]
Great just got the invite, my npm user name is @akulakov.

**Comment by johnotander** [comment]
Added as an owner 😸.

**Comment by aklkv** [comment]
Could you quickly review this pr and merge it please. Thank you.

**Comment by aklkv** [comment]
oh ok, I see now I can review it myself.  I got it if you are busy.

**Comment by johnotander** [comment]
Haha, gave it a preliminary glance which was why I added you as a collaborator : ). Looks good to me 😍

**Pull request merged**
